logLevel: info
logDestinations: [stdout]
api: true
apiAddress: 127.0.0.1:9997
metrics: false
pprof: false
playback: false
rtsp: false
rtmp: false
hls: false
webrtc: true
webrtcAddress: :8889
webrtcAllowOrigins: ["*"]
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: :8189
webrtcIPsFromInterfaces: false
webrtcAdditionalHosts: [192.168.123.18]
srt: false
moq: false
pathDefaults:
  sourceOnDemand: true
  sourceOnDemandStartTimeout: 10s
  sourceOnDemandCloseAfter: 10s
  rtspTransport: tcp
paths:
  z1pro:
    source: rtsp://192.168.144.108/
