const state={active:null,job:null,live:null,view:{yaw:.7,pitch:.55,zoom:28}};
const $=id=>document.getElementById(id);const fmtBytes=n=>`${(n/1024/1024/1024).toFixed(1)} GB 可用`;
async function api(path,options){const r=await fetch(path,options);const j=await r.json();if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);return j}
function sizeCanvas(c){const d=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return[x,w,h]}
function drawTrajectory(){const c=$('trajectory'),[x,w,h]=sizeCanvas(c);x.clearRect(0,0,w,h);x.strokeStyle='#172c42';x.lineWidth=1;for(let i=0;i<w;i+=40){x.beginPath();x.moveTo(i,0);x.lineTo(i,h);x.stroke()}for(let i=0;i<h;i+=40){x.beginPath();x.moveTo(0,i);x.lineTo(w,i);x.stroke()}const t=state.live?.trajectory||[],scale=Math.min(w,h)/11,ox=w/2,oy=h/2;if(t.length){x.strokeStyle='#22d3ee';x.lineWidth=3;x.beginPath();t.forEach((p,i)=>{const px=ox+p[0]*scale,py=oy-p[1]*scale;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();const p=t[t.length-1];x.fillStyle='#fb923c';x.beginPath();x.arc(ox+p[0]*scale,oy-p[1]*scale,7,0,Math.PI*2);x.fill()}}
function drawCloud(canvas,points){const c=canvas,[x,w,h]=sizeCanvas(c);x.clearRect(0,0,w,h);x.fillStyle='#071421';x.fillRect(0,0,w,h);const {yaw,pitch,zoom}=state.view,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);for(const p of points||[]){const a=p[0]*cy-p[1]*sy,b=p[0]*sy+p[1]*cy,z=p[2]||0,px=w/2+a*zoom,py=h*.58-(b*sp+z*cp)*zoom;if(px<0||py<0||px>w||py>h)continue;const hue=185+(z*18);x.fillStyle=`hsla(${hue},85%,${55+(p[3]||.4)*18}%,.8)`;x.fillRect(px,py,2,2)}}
function renderLive(){if(!state.live)return;const d=state.live.device,p=state.live.pose;$('modeBadge').textContent=d.mode==='demo'?'本机演示 · 非真机':'机器狗实时';$('robotState').textContent=d.online?'在线':'离线';$('robotId').textContent=d.message;$('lidarRate').textContent=`${d.lidar_hz.toFixed(1)} Hz`;$('imuRate').textContent=`${d.imu_hz.toFixed(1)} Hz`;$('lidarAge').textContent=d.lidar_age_s===null?'未收到点云':`${d.lidar_age_s.toFixed(2)} 秒前`;$('diskFree').textContent=fmtBytes(d.disk_free_bytes);$('pose').textContent=`${p.x.toFixed(2)}, ${p.y.toFixed(2)}`;$('pointCount').textContent=`${state.live.points.length} 点`;drawTrajectory();drawCloud($('cloud'),state.live.points)}
function renderRecording(){const b=$('recordButton');if(state.active?.state==='recording'){b.textContent='停止录制并开始建图';b.className='stop';$('phase').textContent='正在录制';$('phaseHint').textContent=state.active.session_id;$('recordInfo').textContent=`已采集 ${state.active.sample_count} 帧`}else{b.textContent='开始录制地图';b.className='';$('phase').textContent=state.job?'建图处理中':'观察模式';$('phaseHint').textContent=state.job?.message||'尚未录制';$('recordInfo').textContent='等待开始'}b.disabled=false}
async function toggleRecord(){try{$('recordButton').disabled=true;$('error').textContent='';if(state.active){const out=await api(`/api/v1/sessions/${state.active.session_id}/stop`,{method:'POST'});state.active=null;state.job=out.map_job}else{state.active=await api('/api/v1/sessions/start',{method:'POST'})}await refreshSessions();renderRecording()}catch(e){$('error').textContent=e.message;$('recordButton').disabled=false}}
async function refreshJob(){if(!state.job)return;state.job=await api(`/api/v1/map-jobs/${state.job.job_id}`);$('jobProgress').style.width=`${state.job.progress}%`;$('jobMessage').textContent=state.job.error||state.job.message;if(state.job.state==='complete'){await showResult(state.job);state.job=null;renderRecording()}else if(state.job.state==='failed')state.job=null}
async function showResult(job){$('resultEmpty').style.display='none';$('overview').src=job.overview_url;$('overview').style.display='block';const artifact=await api(job.point_cloud_url);$('resultCloud').style.display='block';drawCloud($('resultCloud'),artifact.points);$('resultMeta').textContent=`${job.metrics.point_count||artifact.points.length} 点 · ${job.metrics.worker}`}
async function refreshSessions(){const data=await api('/api/v1/sessions');$('sessions').innerHTML=data.items.slice(0,8).map(s=>`<div class="session"><div><strong>${s.session_id}</strong><small>${s.sample_count} 帧 · ${s.started_at||''}</small></div><b>${s.state}</b></div>`).join('')||'<div class="empty">暂无录制</div>';const active=data.items.find(s=>s.state==='recording');if(active)state.active=active;else if(!state.job){const latest=data.items.find(s=>s.map_job_id);if(latest)state.job=await api(`/api/v1/map-jobs/${latest.map_job_id}`)}}
async function tick(){try{state.live=await api('/api/v1/live');renderLive();if(state.active){const s=await api(`/api/v1/sessions/${state.active.session_id}`);state.active=s;renderRecording()}await refreshJob()}catch(e){$('error').textContent=e.message}}
let drag=null;const cloud=$('cloud');cloud.addEventListener('pointerdown',e=>drag=[e.clientX,e.clientY]);cloud.addEventListener('pointermove',e=>{if(!drag)return;state.view.yaw+=(e.clientX-drag[0])*.008;state.view.pitch=Math.max(.1,Math.min(1.4,state.view.pitch+(e.clientY-drag[1])*.006));drag=[e.clientX,e.clientY];drawCloud(cloud,state.live?.points)});addEventListener('pointerup',()=>drag=null);cloud.addEventListener('wheel',e=>{e.preventDefault();state.view.zoom=Math.max(8,Math.min(90,state.view.zoom*(e.deltaY>0?.9:1.1)));drawCloud(cloud,state.live?.points)},{passive:false});$('recordButton').addEventListener('click',toggleRecord);addEventListener('resize',()=>{renderLive();if(state.job?.state==='complete')refreshJob()});refreshSessions().then(renderRecording);tick();setInterval(tick,500);
