from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_ROOT = ROOT / "architecture" / "modules"
OUTPUT = ROOT / "docs" / "generated" / "repository-index.md"
LOCK = ROOT / "dependencies" / "capability_migration.lock.json"
REQUIRED = {
    "id", "responsibility", "runtime", "status", "codeRoots", "entrypoints",
    "dependsOn", "consumes", "produces", "sourceProvenance",
}


def load_manifests() -> list[dict]:
    manifests = []
    for path in sorted(MANIFEST_ROOT.glob("*.json")):
        value = json.loads(path.read_text(encoding="utf-8"))
        missing = REQUIRED - value.keys()
        if missing:
            raise ValueError(f"{path}: missing {sorted(missing)}")
        value["_path"] = path.relative_to(ROOT).as_posix()
        manifests.append(value)
    ids = [item["id"] for item in manifests]
    if len(ids) != len(set(ids)):
        raise ValueError("duplicate module id")
    known = set(ids)
    for item in manifests:
        unknown = set(item["dependsOn"]) - known
        if unknown:
            raise ValueError(f"{item['id']}: unknown dependencies {sorted(unknown)}")
        for root in item["codeRoots"]:
            if not (ROOT / root).exists():
                raise ValueError(f"{item['id']}: missing code root {root}")
    return manifests


def snapshot_digest(root: Path) -> tuple[int, str]:
    digest = hashlib.sha256()
    files = sorted(path for path in root.rglob("*") if path.is_file())
    for path in files:
        relative = path.relative_to(root).as_posix().encode()
        digest.update(relative + b"\0" + hashlib.sha256(path.read_bytes()).digest() + b"\0")
    return len(files), digest.hexdigest()


def validate_snapshot() -> None:
    lock = json.loads(LOCK.read_text(encoding="utf-8"))
    expected = lock["localSnapshot"]
    count, digest = snapshot_digest(ROOT / expected["root"])
    if count != expected["fileCount"] or digest != expected["aggregateSha256"]:
        raise ValueError(
            f"locked capability snapshot changed: files={count}, sha256={digest}"
        )


def render(manifests: list[dict]) -> str:
    lines = [
        "# Repository capability index",
        "",
        "> Generated by `python3 tools/knowledge.py write`. Do not edit manually.",
        "",
        "Read `PROJECT_STATE.md` for verified deployment state. A module status in",
        "this index describes code state and never implies robot acceptance.",
        "",
        "| Module | Responsibility | Runtime | Code status | Depends on |",
        "|---|---|---|---|---|",
    ]
    for item in manifests:
        lines.append(
            f"| `{item['id']}` | {item['responsibility']} | "
            f"{', '.join(item['runtime'])} | `{item['status']}` | "
            f"{', '.join(f'`{dep}`' for dep in item['dependsOn']) or '—'} |"
        )
    lines.extend(["", "## Module details", ""])
    for item in manifests:
        lines.extend([
            f"### `{item['id']}`",
            "",
            f"- Manifest: `{item['_path']}`",
            f"- Code roots: {', '.join(f'`{root}`' for root in item['codeRoots']) or 'none yet'}",
            f"- Entrypoints: {', '.join(f'`{entry}`' for entry in item['entrypoints']) or 'none yet'}",
            f"- Consumes: {', '.join(item['consumes']) or 'none'}",
            f"- Produces: {', '.join(item['produces']) or 'none'}",
            f"- Provenance: {'; '.join(item['sourceProvenance'])}",
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=("write", "check"))
    args = parser.parse_args()
    manifests = load_manifests()
    validate_snapshot()
    rendered = render(manifests)
    if args.mode == "write":
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(f"updated {OUTPUT.relative_to(ROOT)}")
        return
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
        raise SystemExit("repository index is stale; run: make knowledge")
    print("repository knowledge: current")


if __name__ == "__main__":
    main()
